[package]
name = "yew-tou-rs"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
path = "src/lib.rs"

[dependencies]
yew = { version = "0.21.0", features = ["csr"] }
serde_json = "1.0.117"
web-sys = { version = "0.3.68", features = ["DomRect"] }
serde = { version = "1.0.203", features = ["derive"] }

[[example]]
name = "basic"
path = "examples/basic.rs"

[[bin]]
name = "example-basic"
path = "examples/basic.rs"