name: GitHub Pages

on:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build_and_deploy_main:
    name: Rust project for main branch
    runs-on: ubuntu-22.04
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: jetli/trunk-action@v0.5.0
        with:
          version: "latest"

      - run: rustup target add wasm32-unknown-unknown
      - run: trunk build --release --public-url /yew-tou-rs/

      - name: Generate Rust docs
        run: cargo doc --no-deps --target-dir target

      - name: Copy docs to publish directory
        run: mv ./examples/dist ./dist

      - name: Copy docs to publish directory
        run: cp -r target/doc dist/doc

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: dist
          keep_files: true
